//
//  DataList.swift
//  NC1_feltrinelli
//
//  Created by Davide Formisano on 15/11/23.
//

import Foundation
import SwiftUI

struct items: Identifiable{
    var id: UUID = UUID()
    var nameLibro: String
    var type: LocalizedStringKey
    var imageLibro: String
    var scrittore: String
    var description: LocalizedStringKey
    var isRecommended: Bool
}

class DataList {
    var lists: [items] = [
        items(nameLibro: "Hunger games", type: "Film", imageLibro: "HungerG", scrittore: "Francis Lawrence, Gary Ross", description: "Hunger Games is a 2012 American drama film directed by Gary Ross, based on the novel of the same name by Suzanne Collins. In a post-apocalyptic future, the nation of Panem is divided into twelve subordinate districts, at the behest of Capitol City and the despotic President Snow. Years earlier, the people rebelled against oppression, but the military repressed the dissidents, destroying the 13th district. Since that day, every year, a boy and a girl from each district participate in the Hunger Games, a cruel and inhumane show, designed to repress any desire for riot. When the District 12 harvest selects Primrose Everdeen, her older sister Katniss offers her place as a tribute. The girl, in fact, has always put the good of the family before herself, risking being punished for the long hunting sessions with his friend Gale Hawthorne. Together with Katniss, the baker’s son Peeta Mellark is extracted. The two are entrusted to the care of former champion Haymitch Abernathy , the extravagant Effie Trinket and the designer Cinna . To prepare for the Hunger Games, the tributes have to go through a hard workout, after which they will get a score that will allow them to have a number of advantages. The games are controlled by some sponsors, who can help participants depending on the audience’s liking. Aware that he has no special talent, Peeta manages to attract the benevolence of viewers, confessing on live television his feelings for Katniss. The girl is furious, but chooses to follow the script studied by Haymitch. When the games begin, Katniss finds the support of the small Rue. The bond of mutual altruism puts in crisis the Strategists of the game, and feeds the hope of the audience. Thanks to her rebellious spirit and the piety she shows towards her enemies, Katniss becomes the symbol of the revolt and Panem acclaims the girl. President Snow, however, cannot allow that happen", isRecommended: true),
        items(nameLibro: "Harry Potter and the Sorcerer's Stone", type: "Film", imageLibro: "HarryPott", scrittore: "Chris Columbus", description: "Harry is an orphan who lives with the awful Dursleys, his aunt, uncle, and cousin. On his 11th birthday, Harry receives a mysterious letter, but his uncle destroys it before he can read it. Letters keep coming, and the Dursleys panic and hide away on a remote island. But they're found by Hagrid, a huge, bearded man with a weakness for scary-looking creatures. It turns out that the letters were coming from Hogwarts, a boarding school for young witches and wizards, and Harry is expected for the fall term, so Hagrid whisks him off to begin his new life as a wizard in training. On the train to Hogwarts, Harry meets his future best friends, Ron Weasley and Hermione Granger. When school begins, things really get exciting, with classes in Potions and Defense Against the Dark Arts, a sport called Quidditch, a mysterious trap door guarded by a three-headed dog named Fluffy, and a baby dragon named Norbert. Throughout the year, Harry adjusts to his magical life and begins to come to grips with his famous status in the wizarding world and what he represents to the darker forces there. He also learns some important lessons about loyalty and courage", isRecommended: true),
        items(nameLibro: "Guerra e pace", type: "Books" ,imageLibro: "GuePac", scrittore: "Lev Nikolaevic Tolstoj", description: "'War' is the historical world, 'peace' is the human world. The human world interests and attracts Tolstoy especially because he is convinced that every man - yesterday, today, tomorrow - is another man...» (Leone Ginzburg). The most authentic narrative epic of modern literature. Against the backdrop of the European crisis of the early nineteenth century, the stories of the members of two families of the Russian high nobility, the Bolkonsky and the Rostov, among whom emerge the figures of Natasa Rostova, Andrei Bolkonsky and Pierre Bezuchov. Tolstoy accompanies the three protagonists, symbols of the harmony of the world, through dances, battles, marriages, deaths, participating directly in their anxieties and giving voice to the inner motions of the heart.", isRecommended: true),
        items(nameLibro: "Matrix", type:"Films", imageLibro: "Matrix", scrittore: "Lana Wachowski, Lilly Wachowski", description: "A world that seems real and is instead just a screen to hide the real reality. Following a tattoo on a girl’s shoulder, the hacker Neo discovers that the so-called 'reality' is just an electrical impulse provided to the brain of humans by an artificial intelligence. The Earth had survived the catastrophe but humanity needed machines to survive. And they won. But machines need men and their energy. The illusion in which they live is to 'cultivate' them better. No one is aware of the time that has passed since the neurosimulator assigned a fictitious date to time. Only Neo, with the help of the computer pirate Morpheus and the beautiful Trinity, can try to discover the truth. But it will not be easy.", isRecommended: true),
        items(nameLibro: "L'educazione delle farfalle", type: "Books", imageLibro: "EdFarfalle", scrittore: "Donato Carrisi", description: "The wooden house burns in the middle of the night. Tongues of fire light up the valley in the mountains. In the silence of the falling snow, only the roar of fire is heard. And when the wooden house collapses, only the frightened whispers of those who managed to escape in time remain. But something is not as it should be. The numbers don’t add up. And fate turns out to be terribly cruel to a mother: Serena. If there is a word with which Serena would never have thought to identify herself, it is the word «mother». She is the «blond shark», a fierce and successful broker in the world of high finance. She is master of her destiny, and no one is her master. But after the fire at the chalet everything changes, and Serena begins to fall into the worst of dreams. What if the maternal instinct you’ve always denied is stronger than fire, destiny, anything in the universe? What if we really knew that we loved someone deeply only when he appeared lost to us forever? This is not simply Donato Carrisi’s latest masterpiece. Because Serena is not a character like the others, and this is not a story like the others. This is an unstoppable journey to discover the darkest corners of our hearts and fears, at the end of which our way of seeing the world will simply never be the same.", isRecommended: false ),
        items(nameLibro: "Riusciranno i nostri eroi a ritrovare l'amico misteriosamente scomparso in Sud America", type: "Books", imageLibro: "SudAmerica", scrittore: "Antonio Manzini", description: "After Old acquaintances and Le ossa parlano, Deputy Commissioner Rocco Schiavone is on an unofficial mission thousands of miles from his hated Aosta, with his old friend Brizio. They want to find Furio, the other companion of a lifetime, disappeared between Buenos Aires, Mexico and Costa Rica. Furio, for his part, threw himself at breakneck speed on the trail of Sebastiano, the fourth of the group, who escaped to South America to escape a terrible guilt and the consequent punishment. The background is far in time and has shaken the lives of all of them. And now Rocco and Brizio must prevent Furio’s «madness», but they also want to understand Seba’s why, what were the deep reasons for that horrible betrayal with which Rocco has already tried to deal, so you can say goodbye to a friendship as old as them. The search appears in vain, because the continent is immense and those who escape leave only fleeting clues, suspended in reality between disappearing and the desire to explain themselves or to expiate. The Deputy Commissioner, as a fine investigator, knows how to arm a reckless hunt, and Brizio is quick enough to support him properly. In this mixture of thriller and psychology, it is inevitable that in Rocco’s mind the many memories of a childhood with the gang in Trastevere, that small world where only a lucky case has decided that Schiavone has become a policeman and not a «bandit»a guard and not a thief, like his inseparable companions, united in a friendship that is no longer there, destroyed by time, fate or perhaps only by personal appetites. Finding Sebastian mysteriously disappeared in South America will perhaps be possible. Impossible to find the friend. Antonio Manzini returns to tell the ghosts of his deputy commissioner, but this time he does it to close a circle, one of the most painful of his life.", isRecommended: true),
        items(nameLibro: "Una ragazza d'altri tempi", type: "BooKs", imageLibro: "RagazzaTempi", scrittore: "Felicia Kingsley", description: "Who would not like to live in London in the early '800, between dances, parties and court invitations? Certainly Rebecca Sheridan would like it, because to her the twenty-first century goes tight: hectic life, zero personal space and men... possible that no one knows how to woo a girl? Brilliant student of Egyptology and passionate reader of romance Regency, Rebecca loves to participate in historical re-enactments in costume and, just during one of these, something inexplicable happens: she finds herself thrown in London of 1816. Overcome the initial shock, realizes that she has a unique opportunity: to be the most contended novice by the bachelors of high society, between tea, dancing and walks in Hyde Park. While he is searching for his Mr Darcy, however, he attracts the attention of the least recommendable man in London: Reedlan Knox, a corsair with dark charm and a reputation nothing short of scandalous. I mean, the kind of man a nice lady shouldn’t be hanging out with. But when Rebecca discovers secret secrets and shady plots of the aristocracy, her sense of justice requires her to investigate. But no one seems willing to risk their honor to help her. All you have to do is turn to the only honor you have to defend: Reedlan Knox. What if, after all, the corsair turns out to be more interesting than the gentleman he always dreamed of? Deciding whether to return to the present or stay in 1816 could become a difficult choice...", isRecommended: true),
        items(nameLibro: "Un giorno questo dolore sarà utile", type: "Books", imageLibro: "DoloreUtile", scrittore: "Peter Cameron", description: "James is 18 years old and lives in New York. After school, he works in his mother’s art gallery, where no one ever enters: it would be difficult, on the other hand, to arouse a clamor around trendy works such as the dustbins of the Japanese artist who wants to remain nameless. To fool the time, and in the hope of finding an alternative to university («I’ve spent my whole life with my peers and I don’t like them very much»), James is online looking for a home in the Midwest where he can peacefully cultivate his favorite activities - reading and solitude -, but luckily for him, the reckless real estate agents will reveal some alarming drawbacks of provincial life. Until one day James enters a lonely hearts chat and, under a false name, proposes to John, the gallery manager who is a compulsive user, a blind date... The dots of suspension are an abused expedient, but in this case proceeding further would be wrong to one of the few writers on the scene who, as you well know who loved That Golden Night, only ask to be read. Anticipating the adventures and thoughts of James would risk overshadowing the singular grace that pervades this book, and from which one lets himself be enveloped long before recognizing, in his restless and melancholy irony, something that few can tell: the air of time.", isRecommended: false),
        items(nameLibro: "Lo sguardo di Medusa", type: "Books", imageLibro: "Medusa", scrittore: "Natalie Haynes", description: "Medusa is the only mortal in a family of gods. Growing up with her sisters, Steno and Euriale, she soon realizes that she is the only one to be vulnerable, cared for precisely because of her fragility and her extraordinary beauty. This makes her sensitive, full of a compassion that immortals struggle to understand and desire to annihilate. When greed drives Poseidon to commit an unforgivable act, Medusa’s life is forever upset: Athena, outraged and jealous, throws her revenge on the innocent girl, transforming it into a Gorgon with snake hair and a look that turns into stone anyone who dares to cross it. Horrified by her powers, Medusa can no longer look at the people she loves without destroying them - the very person who would have wanted to protect them -, and condemns herself to a life of solitude and exile. At least until Perseus, the son of Zeus and Danae, embarks on a heroic feat to win his head. But which one can be called a hero? Which one is really the monster? And more importantly, what does it mean to be a monster? By combining wit with a thorough knowledge of the classics, Natalie Haynes tells us the story of Medusa from an original and multifaceted point of view, leading us to ask ourselves whether beauty belongs only to the body or whether, rather, it should not be sought in the soul. Alternating her voice with that of capricious and fickle gods, the author finally does justice to a character as fascinating as controversial, returning a refined and surprising portrait.", isRecommended: false)
        
    ]
}
